version: '2.1'

services:
  eureka-server:
    build: eureka-server/
    mem_limit: 500m
    ports:
      - 8761:8761
  config-server:
    build: config-server/
    mem_limit: 500m
    ports:
      - 8888:8888
  # gateway:
  #   build: gateway/
  #   mem_limit: 500m
  #   ports:
  #     - 8083:8083
  checkout-service:
    build: checkout-service/
    mem_limit: 500m
    ports:
      - 8081:8080
  product-service:
    build: product-service/
    mem_limit: 500m
    ports:
      - 8084:8080
  payments-service:
    build: payments/
    mem_limit: 500m
    ports:
      - 8082:8080
  notifications-service:
    build: notifications-service/
    mem_limit: 500m
    ports:
      - 8083:8080
